### ISSUE TITLE
http://randomserver.com/?

### ISSUE THREAD

**Issue by ghost** [wallproxy/wallproxy#13]
On the stable instance of Chrome, I load the XNXX website, it is redirected to http://randomserver.com/? But on the Chorme Canery, it won't be redirected to http://randomserver.com/ if I turn the proxy on.
On the Firefox, sometimes. Tonight I load this address http://video.xnxx.com/video1349112/ol_slut_1 without proxy, it is redirected to randomserver.com. But it keeps to be redirected while other pages in this website load fine.
Any ideas?

**Comment by wallproxy** [comment]
Add ||xnxx.com to userlist.ini or proxy extension?
