### ISSUE TITLE
Wallproxy-plugins 2.0如何修改加密方法

### ISSUE THREAD

**Issue by happyangle** [wallproxy/wallproxy#14]
RT..........或者不可以

**Comment by wwqgtxx** [comment]
请作者关闭github的issue区吧！

在 2013年2月7日星期四，happyangle notifications@github.com 写道：

> RT..........或者不可以
> 
> —
> Reply to this email directly or view it on GitHub.

## 

发自移动版 Gmail
wwqgtxx
