### ISSUE TITLE
为什么proxy.py要exec zlib过的代码？

### ISSUE THREAD

**Issue by jwfang** [wallproxy/wallproxy#2]

**Comment by Yonsm** [comment]
因为作者是心胸狭窄的不想、不会和朋友一起玩的人

**Comment by wangchunlei** [comment]
我感觉应该是知道的人越多，越容易被墙

**Comment by jwfang** [comment]
而且代码还加混淆了。。。不懂～

**Comment by wallproxy** [comment]
因为这是这个项目重新维护的主要原因之一。
在完全开源的wallproxy 1.x的时候就是这种框架形式，但直到这个项目几乎消亡，都没有人继续这个项目，所以就没有指望有多少人能来参与这部分代码；这次为了实验一种隐藏Python源码的方式，才重新开始了这个项目。
https://code.google.com/p/wallproxy-plus/issues/detail?id=474#c2

**Comment by phoenixxie0** [comment]
那是不是应该给喜欢看代码的人提供以下方便呢

**Comment by wallproxy** [comment]
直接发出来就失去检验代码处理的效果了，而我手上又没有更值得检验效果的代码；
再者，鉴于wallproxy 1.x的下场，目前是暂不会提供proxy.py的代码的，要是有人愿意接手这个项目的话倒是可以考虑。
