### ISSUE TITLE
这里有提供完整版下载吗？

### ISSUE THREAD

**Issue by ibitr** [wallproxy/wallproxy#5]
以前在code.google上既有提供更新版下载，也有提供完整版下载，现在在github还有提供完整下载吗，在哪里？因为有需要，盼复。

感谢作者的辛勤劳动！

**Comment by wallproxy** [comment]
google code上给的就是这里的链接，切换到win branch再点“↓ZIP”
https://github.com/wallproxy/wallproxy/tree/win

**Comment by ibitr** [comment]
谢谢，知道了。
